# Generated by Django 5.2.4 on 2025-07-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(help_text='The official Pokémon ID from PokéAPI.', unique=True)),
                ('name', models.CharField(help_text='The name of the Pokémon.', max_length=100, unique=True)),
                ('image_url', models.URLField(help_text="URL to the Pokémon's primary digital image (e.g., official artwork from PokéAPI).", max_length=500)),
                ('sprite_front_default_url', models.URLField(blank=True, help_text='URL to the default front sprite.', max_length=500, null=True)),
                ('sprite_back_default_url', models.URLField(blank=True, help_text='URL to the default back sprite.', max_length=500, null=True)),
                ('sprite_front_shiny_url', models.URLField(blank=True, help_text='URL to the shiny front sprite.', max_length=500, null=True)),
                ('sprite_back_shiny_url', models.URLField(blank=True, help_text='URL to the shiny back sprite.', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='A brief description or Pokedex entry for the Pokémon.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the digital image.', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is currently available for sale.')),
                ('types', models.JSONField(default=list, help_text="List of Pokémon types (e.g., ['fire', 'water']).")),
                ('stats', models.JSONField(default=dict, help_text="Dictionary of base stats (e.g., {'hp': 45, 'attack': 49}).")),
                ('abilities', models.JSONField(default=list, help_text='List of Pokémon abilities.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['pokemon_id'],
            },
        ),
    ]
